#pragma once

enum EType
{
	CS_SIGNUP,						// 회원 가입
	SC_SIGNUP,

	CS_LOGIN_TRY,
	SC_LOGIN_TRY,

	CS_XML_DATA,					// XML Data 업로드

	SC_XML_DROP_ITEM,				// XML 파일
	SC_XML_CB_FIRST,
	SC_XML_CB_SECOND,
	SC_XML_EQ_ITEM,
	SC_XML_SHOP_ITEM,
	SC_XML_LEVEL,

	CS_LOGIN_SUCCESS,
	SC_LOGIN_SUCCESS,

	CS_ENTER_ZONE,					// 인게임 맵 입장
	SC_ENTER_ZONE,

	CS_CHANGE_ZONE,					// 인게임 맵 변경
	SC_CHANGE_ZONE,

	SC_MAP_INFO,					// 

	CS_MOVE_INFO,					// 이동 동기화
	SC_MOVE_INFO,

	CS_WORLD_CHAT,					// 월드 채팅
	SC_WORLD_CHAT,

	CS_LEVEL_CHAT,					// Level 채팅
	SC_LEVEL_CHAT,

	CS_WHISPER_CHAT,				// 귓속말
	SC_WHISPER_CHAT,

	SC_ENTER_NEW_PLAYER,			// 새로운 플레이어 입장

	SC_MONSTER_INFO,				// 몬스터 정보

	CS_GATHER_START_INFO,			// 채집 시작
	SC_GATHER_START_INFO,

	CS_GATHER_CANCEL_INFO,			// 채집 취소
	SC_GATHER_CANCEL_INFO,

	SC_GATHER_SUCCESS_INFO,			// 채집 성공

	SC_DROP_ITEM_INFO,				// 드롭 아이템 정보

	SC_INTERACTION_MOVE_INFO,		// 채집물 이동 동기화

	SC_RESPAWN_MONSTER_INFO,		// 몬스터 리스폰

	SC_SPAWN_INTERACTION_INFO,		// 채집물 리스폰 (전체)
	SC_RESPAWN_INTERACTION_INFO,	// 채집물 리스폰 (한개)

	CS_COMBINATION_INFO,			// 아이템 조합
	SC_COMBINATION_INFO,

	CS_THROWITEM_INFO,				// 아이템 버리기
	SC_THROWITEM_INFO,

	CS_MOUNTEQUIPMENT_INFO,			// 장비 아이템 착용
	SC_MOUNTEQUIPMENT_INFO,

	CS_UNMOUNTEQUIPMENT_INFO,		// 장비 아이템 해제
	SC_UNMOUNTEQUIPMENT_INFO,

	CS_TRYTRADE_INFO,				// 교환 신청
	SC_TRYTRADE_INFO,

	SC_TRYTRADE_FAIL,

	CS_TRADEMACTCHING_INFO,			// 교환신청 결과
	SC_TRADEMACTCHING_INFO,

	CS_TRADEPUTONITEM_INFO,			// 아이템 올리기
	SC_TRADEPUTONITEM_INFO,

	CS_TRADEACCEPT_INFO,			// 수락하기
	SC_TRADEACCEPT_INFO,

	CS_TRADECANCEL_INFO,			// 교환 취소
	SC_TRADECANCEL_INFO,

	SC_COMPLETION_INFO,				// 교환 완료

	CS_SHOP_BUY_ITEM,				// 상점 구매
	SC_SHOP_BUY_ITEM,

	CS_ITEMUSE_INFO,				// 아이템 사용
	SC_ITEMUSE_INFO,

	SC_FATIGUE_UPDATE,				// 피로도 회복

	CS_LOGOUT_PLAYER,				// 로그 아웃
	SC_LOGOUT_PLAYER,
};